/* Note: File generated by schema_parse */

#include "parser.h"
#include "parser_defs.h"

#include <stddef.h>

#define TRIE_NODE_PREFIX matroska_semantics

extern const struct elem_data *ebml_data;

DEF_EBML_DATA(6dd70f98c422251c, "XyRF8 -> EBMLSemantics", NULL, 64, &ebml_data);

int matroska_tracknumber_handler(const char *, enum etype, edata_t *, void **, size_t *, void **, size_t *, size_t, size_t, struct buf *, int64_t, void *, int);

DEF_EBML_DATA(ddb2c7846eac7ba2, "L1 -> ElementHandler1", &matroska_tracknumber_handler, 64, NULL);

int matroska_simpleblock_handler(const char *, enum etype, edata_t *, void **, size_t *, void **, size_t *, size_t, size_t, struct buf *, int64_t, void *, int);

DEF_EBML_DATA(0bb25e0546a54357, "X0 -> ElementHandler2", &matroska_simpleblock_handler, 64, NULL);

int matroska_block_handler(const char *, enum etype, edata_t *, void **, size_t *, void **, size_t *, size_t, size_t, struct buf *, int64_t, void *, int);

DEF_EBML_DATA(7e8e21972ffbfa8c, "V0 -> ElementHandler3", &matroska_block_handler, 64, NULL);

int matroska_contentcompalgo_handler(const char *, enum etype, edata_t *, void **, size_t *, void **, size_t *, size_t, size_t, struct buf *, int64_t, void *, int);

DEF_EBML_DATA(4addf55787a7973e, "I72 -> ElementHandler4", &matroska_contentcompalgo_handler, 2, NULL);

int matroska_contentcompsettings_handler(const char *, enum etype, edata_t *, void **, size_t *, void **, size_t *, size_t, size_t, struct buf *, int64_t, void *, int);

DEF_EBML_DATA(a66baeebeba93a1a, "J72 -> ElementHandler5", &matroska_contentcompsettings_handler, 128, NULL);

#define matroska_semantics_TRIE_ROOT (&matroska_semantics_trie_node_13e43b905e15355c)

DEF_TRIE_NODE_INFORMATION(4addf55787a7973e, "I72",
	EBML_DATA(6dd70f98c422251c)
);

DEF_TRIE_NODE_INFORMATION(a66baeebeba93a1a, "J72",
	EBML_DATA(6dd70f98c422251c)
);

DEF_TRIE_NODE_INFORMATION(ddb2c7846eac7ba2, "L1",
	EBML_DATA(6dd70f98c422251c)
);

DEF_TRIE_NODE_INFORMATION(7e8e21972ffbfa8c, "V0",
	EBML_DATA(6dd70f98c422251c)
);

DEF_TRIE_NODE_INFORMATION(0bb25e0546a54357, "X0",
	EBML_DATA(6dd70f98c422251c)
);

DEF_TRIE_NODE_BRANCH(13e43b905e15355c, "NULL",
	ENTRY('I', 4addf55787a7973e),
	ENTRY('J', a66baeebeba93a1a),
	ENTRY('L', ddb2c7846eac7ba2),
	ENTRY('V', 7e8e21972ffbfa8c),
	ENTRY('X', 0bb25e0546a54357)
);

#undef TRIE_NODE_PREFIX

